name: Rust checks
on:
  pull_request:
  push:
    branches: ['**']
permissions:
  contents: read
jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      source: ${{ github.sha }}
  packages:
    needs: checks
    uses: ./.github/workflows/package.yml
    with:
      source: ${{ github.sha }}
      source-ref: ${{ github.ref }}
      channel: check
